// <auto-generated />
using System;
using EWasteManagement.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EWasteManagement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261004095009_AddCsvSubmissions")]
    partial class AddCsvSubmissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EWasteManagement.API.Features.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("StaffType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("staff_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_role", "role IN ('household','corporate','collector','staff','admin')");

                            t.HasCheckConstraint("CK_users_staff_type", "(role = 'staff' AND staff_type IN ('management','worker')) OR (role <> 'staff' AND staff_type IS NULL)");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.Collector", b =>
                {
                    b.Property<Guid>("CollectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<decimal>("CapacityKg")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("capacity_kg");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("CurrentLatitude")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("current_latitude");

                    b.Property<decimal?>("CurrentLongitude")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("current_longitude");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_available");

                    b.Property<DateTime?>("LocationUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("location_updated_at");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(5.0m)
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("CollectorId");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("collectors", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("EstimatedDistanceKm")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("estimated_distance_km");

                    b.Property<int?>("EstimatedEtaMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_eta_minutes");

                    b.Property<string>("MatcherReasoning")
                        .HasColumnType("text")
                        .HasColumnName("matcher_reasoning");

                    b.Property<decimal?>("MeasuredWeightKg")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("measured_weight_kg");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pickup_address");

                    b.Property<decimal?>("PickupLatitude")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("pickup_latitude");

                    b.Property<decimal?>("PickupLongitude")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("pickup_longitude");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<decimal?>("RequiredCapacityKg")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("required_capacity_kg");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<DateTime?>("ScheduledWindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_window_end");

                    b.Property<DateTime?>("ScheduledWindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_window_start");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("JobId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionId");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_jobs_status", "status IN ('assigned','accepted','rejected','inprogress','completed','cancelled','nocollectoravailable','pickuplocationunresolved','awaitingstaffassignment')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.JobAssignmentHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<Guid>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("HistoryId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "CollectorId");

                    b.ToTable("job_assignment_history", null, t =>
                        {
                            t.HasCheckConstraint("CK_job_assignment_history_outcome", "outcome IN ('assigned','accepted','rejected')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Notifications.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("link");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_type", "type IN ('info','success','warning','error')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ClassificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTime>("ClassifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("classified_at");

                    b.Property<Guid?>("ClassifiedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("classified_by_staff_id");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final");

                    b.Property<Guid?>("OverriddenByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("overridden_by_staff_id");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("override_reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("source");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_category");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("classification_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_classification_records_category", "category IN ('reusable','localrecyclable','hazardous','exportonly')");

                            t.HasCheckConstraint("ck_classification_records_source", "source IN ('manual','ai')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.CollectorDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("ReceivedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("received_by_staff_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("collector_deliveries", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.CollectorPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CalculationSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("calculation_snapshot");

                    b.Property<Guid>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_staff_id");

                    b.Property<Guid?>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaidByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_staff_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("collector_payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_collector_payments_source_type", "source_type IN ('job','extrawaste')");

                            t.HasCheckConstraint("ck_collector_payments_status", "status IN ('pending','paid')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("ReceivedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("received_by_staff_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("extra_waste_receipts", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExtraWasteReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("extra_waste_receipt_id");

                    b.Property<Guid?>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_type");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("weight_kg");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExtraWasteReceiptId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("extra_waste_receipt_items", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_location_id");

                    b.Property<Guid?>("ExtraWasteReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("extra_waste_receipt_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_type");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("unit")
                        .HasColumnName("kind");

                    b.Property<string>("OriginType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin_type");

                    b.Property<Guid?>("ParentInventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_inventory_item_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<decimal>("VerifiedWeightKg")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("verified_weight_kg");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("ExtraWasteReceiptId");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasFilter("job_id IS NOT NULL");

                    b.HasIndex("ParentInventoryItemId");

                    b.ToTable("inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_items_kind", "kind IN ('unit','component','material')");

                            t.HasCheckConstraint("ck_inventory_items_origin_type", "origin_type IN ('jobcollection','extrawaste')");

                            t.HasCheckConstraint("ck_inventory_items_status", "status IN ('received','sorting','dismantling','classified','readyforsale','exportonly','onhold','recovered')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ProcessingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid>("PerformedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_staff_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("processing_logs", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.RatePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_type");

                    b.Property<decimal>("RatePerKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rate_per_kg");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ItemType")
                        .IsUnique()
                        .HasFilter("is_active = true");

                    b.ToTable("rate_policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "Laptop",
                            RatePerKg = 50m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "Mobile Phone",
                            RatePerKg = 80m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "Battery",
                            RatePerKg = 30m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "General Household Electronics",
                            RatePerKg = 40m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "GeneralCollection",
                            RatePerKg = 20m
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.WarehouseLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("warehouse_locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Where collector deliveries and extra-waste drop-offs are first received and weighed.",
                            Name = "Receiving Bay"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Items are sorted by category before dismantling or direct classification.",
                            Name = "Sorting Area"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Items are broken down into separately trackable child components.",
                            Name = "Dismantling Area"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classified items awaiting handoff to Component D.",
                            Name = "Ready-for-Sale Storage"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quarantine for items on hold, including everything classified Hazardous.",
                            Name = "Hazardous Hold Area"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAt = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Export-grade items reserved for export channels.",
                            Name = "Export Storage"
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ApprovalAction", b =>
                {
                    b.Property<Guid>("ApprovalActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("approval_action_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action_type");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comments");

                    b.Property<Guid>("CommercialPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("commercial_plan_id");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.HasKey("ApprovalActionId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("CommercialPlanId", "PerformedAt");

                    b.ToTable("approval_actions", null, t =>
                        {
                            t.HasCheckConstraint("CK_approval_actions_type", "action_type IN ('submitted','revisionrequested','approved','rejected')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.Buyer", b =>
                {
                    b.Property<Guid>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("buyer_type");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("BuyerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("buyers", null, t =>
                        {
                            t.HasCheckConstraint("CK_buyers_status", "status IN ('pending','active','suspended')");

                            t.HasCheckConstraint("CK_buyers_type", "buyer_type IN ('local','export')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.CommercialPlan", b =>
                {
                    b.Property<Guid>("CommercialPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("commercial_plan_id");

                    b.Property<bool>("ApprovalRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("approval_required");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DestinationCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destination_country");

                    b.Property<decimal>("EstimatedCosts")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("estimated_costs");

                    b.Property<decimal>("EstimatedNetValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("estimated_net_value");

                    b.Property<decimal>("ExpectedRevenue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("expected_revenue");

                    b.Property<string>("MaterialsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("materials_json");

                    b.Property<string>("ReasoningSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reasoning_summary");

                    b.Property<string>("RecommendedRoute")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recommended_route");

                    b.Property<string>("RiskFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_flags");

                    b.Property<Guid?>("SelectedBuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_buyer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("CommercialPlanId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SelectedBuyerId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowId");

                    b.ToTable("commercial_plans", null, t =>
                        {
                            t.HasCheckConstraint("CK_commercial_plans_costs_non_negative", "estimated_costs >= 0");

                            t.HasCheckConstraint("CK_commercial_plans_revenue_non_negative", "expected_revenue >= 0");

                            t.HasCheckConstraint("CK_commercial_plans_route", "recommended_route IN ('localsale','export')");

                            t.HasCheckConstraint("CK_commercial_plans_status", "status IN ('draft','pendingapproval','approved','rejected','revisionrequested','executed')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrder", b =>
                {
                    b.Property<Guid>("ExportOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("export_order_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destination_country");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("ShipmentDate")
                        .HasColumnType("date")
                        .HasColumnName("shipment_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_value");

                    b.Property<decimal>("TotalWeightKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_weight_kg");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExportOrderId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationCountry");

                    b.HasIndex("Status", "OrderDate");

                    b.ToTable("export_orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_export_orders_status", "status IN ('draft','pendingapproval','approved','shipped','completed','cancelled')");

                            t.HasCheckConstraint("CK_export_orders_value_non_negative", "total_value >= 0");

                            t.HasCheckConstraint("CK_export_orders_weight_non_negative", "total_weight_kg >= 0");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrderItem", b =>
                {
                    b.Property<Guid>("ExportOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("export_order_item_id");

                    b.Property<Guid>("ExportOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("export_order_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("line_total");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantity_kg");

                    b.Property<Guid>("RecoveredMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovered_material_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("ExportOrderItemId");

                    b.HasIndex("ExportOrderId");

                    b.HasIndex("RecoveredMaterialId");

                    b.ToTable("export_order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_export_order_items_price", "unit_price >= 0");

                            t.HasCheckConstraint("CK_export_order_items_qty", "quantity_kg > 0");

                            t.HasCheckConstraint("CK_export_order_items_total", "line_total >= 0");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.MaterialPricing", b =>
                {
                    b.Property<Guid>("PricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal>("PricePerKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_per_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PricingId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MaterialType")
                        .IsUnique()
                        .HasDatabaseName("IX_material_pricing_material_type_approved_unique")
                        .HasFilter("status = 'approved'");

                    b.HasIndex("MaterialType", "EffectiveDate")
                        .IsUnique();

                    b.HasIndex("MaterialType", "Status");

                    b.ToTable("material_pricing", null, t =>
                        {
                            t.HasCheckConstraint("CK_material_pricing_dates", "expiry_date IS NULL OR expiry_date > effective_date");

                            t.HasCheckConstraint("CK_material_pricing_price_positive", "price_per_kg > 0");

                            t.HasCheckConstraint("CK_material_pricing_status", "status IN ('draft','approved','expired')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.MaterialRequest", b =>
                {
                    b.Property<Guid>("MaterialRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("material_request_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<Guid?>("CommercialPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("commercial_plan_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastMatchingNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_matching_note");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MaterialRequestId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CommercialPlanId")
                        .IsUnique();

                    b.HasIndex("Status", "MaterialType");

                    b.ToTable("material_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_material_requests_quantity_positive", "quantity_kg > 0");

                            t.HasCheckConstraint("ck_material_requests_status", "status IN ('waiting','waitingforprice','generatingplan','plangenerated','plangenerationfailed','orderplaced','fulfilled','cancelled')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.RevenueTransaction", b =>
                {
                    b.Property<Guid>("RevenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("revenue_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remarks");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transaction_type");

                    b.HasKey("RevenueId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType", "ReferenceId")
                        .IsUnique();

                    b.ToTable("revenue_transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_revenue_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("CK_revenue_transactions_type", "transaction_type IN ('localsale','export')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrder", b =>
                {
                    b.Property<Guid>("SalesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sales_order_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("MaterialRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_request_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PendingMaterialType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pending_material_type");

                    b.Property<decimal?>("PendingQuantityKg")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("pending_quantity_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SalesOrderId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MaterialRequestId")
                        .IsUnique();

                    b.HasIndex("Status", "OrderDate");

                    b.ToTable("sales_orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_sales_orders_status", "status IN ('waitingforstock','waitingforprice','pendingplanapproval','draft','confirmed','completed','cancelled')");

                            t.HasCheckConstraint("CK_sales_orders_total_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrderItem", b =>
                {
                    b.Property<Guid>("SalesOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sales_order_item_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("line_total");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantity_kg");

                    b.Property<Guid>("RecoveredMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovered_material_id");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_order_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("SalesOrderItemId");

                    b.HasIndex("RecoveredMaterialId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("sales_order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_sales_order_items_price_non_negative", "unit_price >= 0");

                            t.HasCheckConstraint("CK_sales_order_items_quantity_positive", "quantity_kg > 0");

                            t.HasCheckConstraint("CK_sales_order_items_total_non_negative", "line_total >= 0");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Workflow.Entities.AgentExecutionLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent_name");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.Property<bool>("Succeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("succeeded");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("LogId");

                    b.HasIndex("AgentName");

                    b.HasIndex("WorkflowId", "StepNumber");

                    b.ToTable("agent_execution_logs", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Workflow.Entities.CollectionWorkflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<string>("AnalyzerResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("analyzer_result_json");

                    b.Property<bool>("ApprovalRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("approval_required");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FinalReasoningSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("final_reasoning_summary");

                    b.Property<string>("MatcherResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("matcher_result_json");

                    b.Property<string>("PlanJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_json");

                    b.Property<Guid?>("ResultingJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("resulting_job_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidatorResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("validator_result_json");

                    b.HasKey("WorkflowId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionId");

                    b.ToTable("collection_workflows", null, t =>
                        {
                            t.HasCheckConstraint("CK_collection_workflows_status", "status IN ('planning','analyzing','validating','pendingapproval','matching','finalizing','completed','rejected','failed')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Workflow.Entities.WorkflowApprovalAction", b =>
                {
                    b.Property<Guid>("WorkflowApprovalActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_approval_action_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action_type");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("WorkflowApprovalActionId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("WorkflowId", "PerformedAt");

                    b.ToTable("workflow_approval_actions", null, t =>
                        {
                            t.HasCheckConstraint("CK_workflow_approval_actions_type", "action_type IN ('submitted','revisionrequested','approved','rejected')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.SubmissionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryHint")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionItems");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.Collector", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.Job", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Collection.Entities.Collector", "CollectorEntity")
                        .WithMany()
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CollectorEntity");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Notifications.Entities.Notification", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ClassificationRecord", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.CollectorPayment", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.CollectorDelivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceiptItem", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceipt", "ExtraWasteReceipt")
                        .WithMany("Items")
                        .HasForeignKey("ExtraWasteReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExtraWasteReceipt");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.InventoryItem", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.WarehouseLocation", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceipt", "ExtraWasteReceipt")
                        .WithMany()
                        .HasForeignKey("ExtraWasteReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.InventoryItem", "ParentInventoryItem")
                        .WithMany()
                        .HasForeignKey("ParentInventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentLocation");

                    b.Navigation("ExtraWasteReceipt");

                    b.Navigation("ParentInventoryItem");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ProcessingLog", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ApprovalAction", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.CommercialPlan", "CommercialPlan")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("CommercialPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommercialPlan");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.Buyer", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("EWasteManagement.API.Features.Sales.Entities.Buyer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.CommercialPlan", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.Buyer", "SelectedBuyer")
                        .WithMany()
                        .HasForeignKey("SelectedBuyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SelectedBuyer");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrder", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.Buyer", "Buyer")
                        .WithMany("ExportOrders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrderItem", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.ExportOrder", "ExportOrder")
                        .WithMany("Items")
                        .HasForeignKey("ExportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportOrder");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.MaterialPricing", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.MaterialRequest", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.CommercialPlan", "CommercialPlan")
                        .WithMany()
                        .HasForeignKey("CommercialPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Buyer");

                    b.Navigation("CommercialPlan");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.RevenueTransaction", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrder", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.Buyer", "Buyer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.MaterialRequest", "MaterialRequest")
                        .WithOne("SalesOrder")
                        .HasForeignKey("EWasteManagement.API.Features.Sales.Entities.SalesOrder", "MaterialRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Buyer");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrderItem", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.SalesOrder", "SalesOrder")
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Workflow.Entities.WorkflowApprovalAction", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Workflow.Entities.CollectionWorkflow", "Workflow")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.SubmissionItem", b =>
                {
                    b.HasOne("EWasteManagement.Api.Entities.Submission", null)
                        .WithMany("Items")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.Buyer", b =>
                {
                    b.Navigation("ExportOrders");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.CommercialPlan", b =>
                {
                    b.Navigation("ApprovalActions");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.MaterialRequest", b =>
                {
                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Workflow.Entities.CollectionWorkflow", b =>
                {
                    b.Navigation("ApprovalActions");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.Submission", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
